auth:
  jwt:
    secret: ${JWT_SECRET_KEY:}
  request:
    secret: ${REQUEST_SECRET_KEY:}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect